/// Pasteboard type identifiers as plain strings, so the core does not depend on AppKit.
public enum PasteboardTypes {
  public static let string = "public.utf8-plain-text"
  public static let rtf = "public.rtf"
  public static let html = "public.html"
  public static let fileURL = "public.file-url"
  public static let url = "public.url"

  public static let png = "public.png"
  public static let tiff = "public.tiff"
  public static let jpeg = "public.jpeg"
  public static let heic = "public.heic"
  public static let gif = "com.compuserve.gif"

  /// Image types in order of preference. The analyzer keeps only the first one present.
  public static let images = [png, gif, heic, jpeg, tiff]
  public static let text = [string, rtf, html, url]
  public static let files = [fileURL]

  // See http://nspasteboard.org.
  public static let concealed = "org.nspasteboard.ConcealedType"
  public static let transient = "org.nspasteboard.TransientType"
  public static let autoGenerated = "org.nspasteboard.AutoGeneratedType"
  public static let source = "org.nspasteboard.source"

  public static let universalClipboard = "com.apple.is-remote-clipboard"

  /// Marks pasteboard contents that Maccy wrote itself.
  public static let fromMaccy = "com.pgilad.Maccy.marker"

  /// Types that must never be saved.
  public static let alwaysIgnored: Set<String> = [concealed, transient, autoGenerated]

  /// Types that password managers and similar apps put on the pasteboard.
  public static let defaultIgnored: Set<String> = [
    "Pasteboard generator type",
    "com.agilebits.onepassword",
    "com.typeit4me.clipping",
    "de.petermaurer.TransientPasteboardType",
    "net.antelle.keeweb",
  ]
}

public enum DefaultIgnoredApps {
  /// Password managers. Their copies often lack the concealed marker.
  public static let bundleIDs: [String] = [
    "com.1password.1password",
    "com.agilebits.onepassword7",
    "com.apple.Passwords",
    "com.apple.keychainaccess",
    "com.bitwarden.desktop",
    "org.keepassxc.keepassxc",
    "com.dashlane.dashlanephonefinal",
  ]
}
